# declare python version
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
  - pip install coveralls
before_script:
  - psql -c 'CREATE DATABASE test_database;' -U postgres
  # - psql -c 'CREATE USER Myko WITH PASSWORD '1987'; -U Myko
  # - psql -c 'GRANT ALL PRIVILEGES ON DATABASE test_database TO Myko;' -U Myko
script:
  - py.test
  - py.test --cov
branches:
  only:
    - ap1-v3-ft-#161573359-signup-login-logout
services:
  - postgresql
addons:
  postgresql: "9.4"
after_success:
  - coveralls
